name: Unit Tests

on: [push]

defaults:
    run:
        shell: bash

jobs:
    run_unit_tests:

        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]

        name: Unit Tests
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Create Build Directory
              run: mkdir build

            - name: Generate Project Files
              working-directory: build
              run: cmake .. -DCMAKE_BUILD_TYPE=Release

            - name: Build Dynamic Library and Unit Tests
              working-directory: build
              run: cmake --build .

            - name: Run Unit Tests
              run: ./unit_tests

            - name: Send Coverage to codecov.io
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: bash <(curl -s https://codecov.io/bash)
