name: Unit Tests

on: [push]

defaults:
    run:
        shell: bash

jobs:
    run_unit_tests:
        name: Unit Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install gtest and gcov
              run: |
                sudo apt-get update
                sudo apt-get install -y libgtest-dev gcovr

            - name: Unit Tests
              working-directory: tests
              run: |
                g++ -std=c++11 -fPIC -shared myDynLib.cpp -o myDynLib.so
	              g++ -std=c++11 tests.cpp -o tests_run -ldl -lgtest -lpthread
	              ./tests_run
